### ISSUE TITLE
Blog link not clickable

### ISSUE THREAD

**Issue by dvberkel** [kcunning/Katie-s-Rougish-PyGame#17]
On the landing page of [Katie-s-Rougish-PyGame](https://github.com/kcunning/Katie-s-Rougish-PyGame) is a description of the project. The description mentions a link to the blog in which the progress is reported. Unfortunately the link is not clickable.

I would be nice if the project description would have a clickable link to the blog.

For example the blog could be added as website to the project.

**Comment by kcunning** [comment]
How did I miss that part of the description? Either they just added it, or I'm blind. 

Anyway, done!

**Comment by dvberkel** [comment]
Thanks!

Keep up the great work
