### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by jul** [kcunning/Katie-s-Rougish-PyGame#31]
I am trying to have a sponsorship from my company, and they not only have issues with IP (are they safe using these courses?) but they would be also willing to contribute back to the project. 

Would it be possible to have a licence that is free as in free software?  

my proposition: 
- License art libre because it is stylish http://artlibre.org/licence/lal/en (OSI approved and RMS blessed)
- any OSI apporoved license including PSF2.0, BSD, CC-BY NA ....

**Comment by kcunning** [comment]
It is free as in speech :) Feel free to remix and reuse.

You can consider this project CC-BY. Thanks for reminding me to add that to the docs!

**Comment by merwok** [comment]
I like the free CC licences for material, but they are discouraged for code: http://wiki.creativecommons.org/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F

Just making a note, I don’t have a concrete proposal :/
