### ISSUE TITLE
Combat!

### ISSUE THREAD

**Issue by kcunning** [kcunning/Katie-s-Rougish-PyGame#8]
The outline of a round of basic combat with dumb monsters:
- Player moves against monster
- Combat is initiated
- Player attempts to hit monster
- Monster attempts to hit Player
- Everything else on the board moves
- Combat is done, player can move again

**Comment by Horatio-Blackwood** [comment]
Hey Katie,

I snagged this code last night (after watching your Pycon tutorial video) and noticed that it appears as though the Combat module that is referenced in game.py is not included in the repo currently.  Are you currently working on an implementation locally that isn't checked in?

Thanks!
- Horatio

**Comment by kcunning** [comment]
D'oh! I always do that. It's checked in now!

**Comment by Horatio-Blackwood** [comment]
Thanks!  Its not a problem.  Just wanted to see if I was missing something.  ;)
